var version = '1.1.5';
var author = '2002-2003';
var loading = 0;
var mainBody;
var width;
var height;
var ajax;
var TS;
var text;
var a = document.createElement('a');
var img;
var ANLT = [];
var NLTN;
var NLT;
var NLTM = [];
var PD;
var CS;
var PI;
var PT;
var PS;
var PM;
var MS;
var DS;
var AS;
var FS;
var PA;
var PN;
var IT = [];
var BS = [];
var DBS;
var PBW;
var PBH;
var IBH;
var PLS = [];
var PRL;
var PST = [];
var PNGI = [];
var PSL;
var PSO = 0;
var PSN;
var PCS;
var PCT;
var PCN = 0;
var PIBMMT;
var PW = [];
var PH = [];
var PRS = [];
var PT = [];
var PL = [];
var PNW = [];
var PNH = [];
var AY = [];
var AZ = [];
var ESX = [];
var ESY = [];
var EOX = [];
var EOY = [];
var PTX = [];
var PTY = [];
var PLTX = [];
var PLTY = [];
var MBW;
var MBH;
var MBX;
var MBY;
var MX;
var MY;
var SPB;
var SP;


var SBB = document.createElement('div');
var SB;
var SDB;
var main = document.getElementsByTagName('main')[0];
var PBB = document.createElement('div');
var PB;
var P;
var PIB = document.createElement('div');
var PIBM = document.createElement('div');
var PMB = document.createElement('div');
var PMP = document.createElement('img');

var BB;
var B;
var NB;
var DB;
var LB;
var RB;
var TM;
var STMB;
var SIPM;
var SISM;
var SIAM;
var TB = document.createElement('div');
var TMB;
var TBC = document.createElement('div');
var IB = document.createElement('div');
var IBC = document.createElement('div');
var ICB = document.createElement('div');
var IPB = document.createElement('div');
var ISB = document.createElement('div');
var IAB = document.createElement('div');
var IPM;
var ISM;
var IAM;


/* 开始执行函数 */
nameSet();
function nameSet(){
    mainBody = main.innerHTML;
    PSG();
}